<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CardTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('card')->delete();

        DB::table('card')->insert(array(
            0 =>
            array(
                'name' => 'Air Raid',
                'type' => 'Spell',
                'mana' => 4,
                'attack' => 0,
                'health' => 0,
                'description' => 'Summon two 1/1 Silver Hand Recruits with Taunt.',
                'is_legendary' => 0,
                'photo' => 'public/Air_Raid_full.jpg',
                'category_id' => 1,
            ),
            1 =>
            array(
                'name' => 'Arena Fanatic',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 2,
                'health' => 3,
                'description' => 'Fanatic of the Arena.',
                'is_legendary' => 0,
                'photo' => 'public/ArenaFanatic.jpg',
                'category_id' => 1,
            ),
            2 =>
            array(
                'name' => 'Barnabus',
                'type' => 'Minion',
                'mana' => 5,
                'attack' => 4,
                'health' => 5,
                'description' => 'Barnabus the Cursed.',
                'is_legendary' => 1,
                'photo' => 'public/Barnabus.jpg',
                'category_id' => 2,
            ),
            3 =>
            array(
                'name' => 'Battlefiend',
                'type' => 'Minion',
                'mana' => 2,
                'attack' => 3,
                'health' => 2,
                'description' => 'A fierce battlefiend.',
                'is_legendary' => 0,
                'photo' => 'public/Battlefiend_full.jpg',
                'category_id' => null,
            ),
            4 =>
            array(
                'name' => 'Beckoner',
                'type' => 'Spell',
                'mana' => 4,
                'attack' => 0,
                'health' => 0,
                'description' => 'Summons a beckoning servant.',
                'is_legendary' => 0,
                'photo' => 'public/Beckoner.jpg',
                'category_id' => 4,
            ),
            5 =>
            array(
                'name' => 'BigTime',
                'type' => 'Minion',
                'mana' => 6,
                'attack' => 5,
                'health' => 6,
                'description' => 'Big Time!',
                'is_legendary' => 0,
                'photo' => 'public/BigTime.jpg',
                'category_id' => null,
            ),
            6 =>
            array(
                'name' => 'Biology Project',
                'type' => 'Spell',
                'mana' => 2,
                'attack' => 0,
                'health' => 0,
                'description' => 'A biological breakthrough.',
                'is_legendary' => 0,
                'photo' => 'public/BiologyProject.jpg',
                'category_id' => 2,
            ),
            7 =>
            array(
                'name' => 'Black Whelp',
                'type' => 'Minion',
                'mana' => 1,
                'attack' => 1,
                'health' => 2,
                'description' => 'A small black whelp.',
                'is_legendary' => 0,
                'photo' => 'public/BlackWhelp.jpg',
                'category_id' => 3,
            ),
            8 =>
            array(
                'name' => 'Blade Dance',
                'type' => 'Spell',
                'mana' => 3,
                'attack' => 0,
                'health' => 0,
                'description' => 'A dance of blades.',
                'is_legendary' => 0,
                'photo' => 'public/Blade_Dance_full.jpg',
                'category_id' => 4,
            ),
            9 =>
            array(
                'name' => 'Blizzard',
                'type' => 'Spell',
                'mana' => 6,
                'attack' => 0,
                'health' => 0,
                'description' => 'Deal 3 damage to all enemy minions and freeze them.',
                'is_legendary' => 0,
                'photo' => 'public/Blizzard.jpg',
                'category_id' => null,
            ),
            10 =>
            array(
                'name' => 'Bruiser',
                'type' => 'Minion',
                'mana' => 5,
                'attack' => 4,
                'health' => 6,
                'description' => 'A tough bruiser.',
                'is_legendary' => 0,
                'photo' => 'public/Bruiser.jpg',
                'category_id' => 1
            ),
            11 =>
            array(
                'name' => 'Chenvaala',
                'type' => 'Minion',
                'mana' => 6,
                'attack' => 4,
                'health' => 6,
                'description' => 'Chenvaala brings icy powers.',
                'is_legendary' => 1,
                'photo' => 'public/Chenvaala_full.jpg',
                'category_id' => 2
            ),
            12 =>
            array(
                'name' => 'Chillblade',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 2,
                'health' => 3,
                'description' => 'A chilling blade wielder.',
                'is_legendary' => 0,
                'photo' => 'public/Chillblade.jpg',
                'category_id' => 3,
            ),
            13 =>
            array(
                'name' => 'Command the Illidari',
                'type' => 'Spell',
                'mana' => 7,
                'attack' => 0,
                'health' => 0,
                'description' => 'Command the Illidari with fierce power.',
                'is_legendary' => 0,
                'photo' => 'public/Command_the_Illidari_full.jpg',
                'category_id' => 4,
            ),
            14 =>
            array(
                'name' => 'Corrupted',
                'type' => 'Spell',
                'mana' => 4,
                'attack' => 0,
                'health' => 0,
                'description' => 'Corrupt the power of your enemies.',
                'is_legendary' => 0,
                'photo' => 'public/Corrupted.jpg',
                'category_id' => null,
            ),
            15 =>
            array(
                'name' => 'Ctun',
                'type' => 'Minion',
                'mana' => 8,
                'attack' => 10,
                'health' => 10,
                'description' => 'A mighty titan with great power.',
                'is_legendary' => 1,
                'photo' => 'public/Ctun.jpg',
                'category_id' => 2,
            ),
            16 =>
            array(
                'name' => 'Cult Neophyte',
                'type' => 'Minion',
                'mana' => 2,
                'attack' => 2,
                'health' => 3,
                'description' => 'A cultist with dangerous powers.',
                'is_legendary' => 0,
                'photo' => 'public/Cult_Neophyte_full.jpg',
                'category_id' => null,
            ),
            17 =>
            array(
                'name' => 'Dinotamer Brann',
                'type' => 'Minion',
                'mana' => 7,
                'attack' => 6,
                'health' => 7,
                'description' => 'Brann brings his dinosaurs to the battlefield.',
                'is_legendary' => 1,
                'photo' => 'public/Dinotamer_Brann_full.jpg',
                'category_id' => 2,
            ),
            18 =>
            array(
                'name' => 'Dragonbane',
                'type' => 'Minion',
                'mana' => 5,
                'attack' => 6,
                'health' => 4,
                'description' => 'A hunter of dragons.',
                'is_legendary' => 1,
                'photo' => 'public/Dragonbane_full.jpg',
                'category_id' => 3,
            ),
            19 =>
            array(
                'name' => 'Dwarven Sharpshooter',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 2,
                'health' => 4,
                'description' => 'A sharpshooter with precision aim.',
                'is_legendary' => 0,
                'photo' => 'public/Dwarven_Sharpshooter_full.jpg',
                'category_id' => 4,
            ),
            20 =>
            array(
                'name' => 'FelOrc',
                'type' => 'Minion',
                'mana' => 4,
                'attack' => 5,
                'health' => 3,
                'description' => 'A fierce Fel Orc warrior.',
                'is_legendary' => 0,
                'photo' => 'public/FelOrc.jpg',
                'category_id' => 3,
            ),
            21 =>
            array(
                'name' => 'Finja',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 3,
                'health' => 4,
                'description' => 'Finja the fish hunter.',
                'is_legendary' => 1,
                'photo' => 'public/Finja.jpg',
                'category_id' => 2,
            ),
            22 =>
            array(
                'name' => 'Fleethoof Pearltusk',
                'type' => 'Minion',
                'mana' => 5,
                'attack' => 4,
                'health' => 6,
                'description' => 'A swift and sturdy tusk.',
                'is_legendary' => 0,
                'photo' => 'public/Fleethoof_Pearltusk_full.jpg',
                'category_id' => 4,
            ),
            23 =>
            array(
                'name' => 'Frozen',
                'type' => 'Spell',
                'mana' => 3,
                'attack' => 0,
                'health' => 0,
                'description' => 'Freeze a target enemy minion.',
                'is_legendary' => 0,
                'photo' => 'public/Frozen.jpg',
                'category_id' => 4,
            ),
            24 =>
            array(
                'name' => 'Galakrond the Nightmare',
                'type' => 'Minion',
                'mana' => 9,
                'attack' => 7,
                'health' => 9,
                'description' => 'Galakrond unleashed in all his glory.',
                'is_legendary' => 1,
                'photo' => 'public/Galakrond2C_the_Nightmare_full.jpg',
                'category_id' => null,
            ),
            25 =>
            array(
                'name' => 'Heistbaron Togwaggle',
                'type' => 'Minion',
                'mana' => 6,
                'attack' => 5,
                'health' => 5,
                'description' => 'A heist mastermind.',
                'is_legendary' => 1,
                'photo' => 'public/Heistbaron_Togwaggle_full.jpg',
                'category_id' => 2,
            ),
            26 =>
            array(
                'name' => 'Kael 27th as Sunstrider',
                'type' => 'Minion',
                'mana' => 8,
                'attack' => 5,
                'health' => 7,
                'description' => 'The great Kael’thas.',
                'is_legendary' => 1,
                'photo' => 'public/Kael27thas_Sunstrider_full.jpg',
                'category_id' => 2,
            ),
            27 =>
            array(
                'name' => 'Kalimos',
                'type' => 'Minion',
                'mana' => 7,
                'attack' => 4,
                'health' => 8,
                'description' => 'Kalimos brings the power of the elements.',
                'is_legendary' => 1,
                'photo' => 'public/Kalimos.jpg',
                'category_id' => 2,
            ),
            28 =>
            array(
                'name' => 'Khartut Defender',
                'type' => 'Minion',
                'mana' => 4,
                'attack' => 3,
                'health' => 6,
                'description' => 'Khartut, a mighty defender.',
                'is_legendary' => 0,
                'photo' => 'public/Khartut_Defender_full.jpg',
                'category_id' => null,
            ),
            29 =>
            array(
                'name' => 'Lakkari',
                'type' => 'Minion',
                'mana' => 6,
                'attack' => 5,
                'health' => 6,
                'description' => 'Lakkari, the dark knight.',
                'is_legendary' => 1,
                'photo' => 'public/Lakkari.jpg',
                'category_id' => 2,
            ),
            30 =>
            array(
                'name' => 'Leeroy',
                'type' => 'Minion',
                'mana' => 5,
                'attack' => 6,
                'health' => 2,
                'description' => 'Leeroy Jenkins charges into battle.',
                'is_legendary' => 1,
                'photo' => 'public/Leeroy.jpg',
                'category_id' => 2,
            ),
            31 =>
            array(
                'name' => 'Lesser Jasper',
                'type' => 'Minion',
                'mana' => 2,
                'attack' => 1,
                'health' => 2,
                'description' => 'A lesser Jasper, weak but persistent.',
                'is_legendary' => 0,
                'photo' => 'public/LesserJasper.jpg',
                'category_id' => 3,
            ),
            32 =>
            array(
                'name' => 'Madame Lazul',
                'type' => 'Minion',
                'mana' => 5,
                'attack' => 3,
                'health' => 5,
                'description' => 'Madame Lazul, a fortune-teller.',
                'is_legendary' => 1,
                'photo' => 'public/Madame_Lazul_full.jpg',
                'category_id' => 2,
            ),
            33 =>
            array(
                'name' => 'Maiev Shadowsong',
                'type' => 'Minion',
                'mana' => 6,
                'attack' => 5,
                'health' => 6,
                'description' => 'Maiev Shadowsong, a fierce warrior.',
                'is_legendary' => 1,
                'photo' => 'public/Maiev_Shadowsong_29_full.jpg',
                'category_id' => null,
            ),
            34 =>
            array(
                'name' => 'Mankrik',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 3,
                'health' => 4,
                'description' => 'Mankrik, a brave warrior.',
                'is_legendary' => 0,
                'photo' => 'public/Mankrik_full.jpg',
                'category_id' => 1,
            ),
            35 =>
            array(
                'name' => 'Medivh',
                'type' => 'Minion',
                'mana' => 7,
                'attack' => 5,
                'health' => 7,
                'description' => 'Medivh, the Guardian of Tirisfal.',
                'is_legendary' => 1,
                'photo' => 'public/Medivh.jpg',
                'category_id' => 2,
            ),
            36 =>
            array(
                'name' => 'Moarg Artificer',
                'type' => 'Minion',
                'mana' => 4,
                'attack' => 3,
                'health' => 5,
                'description' => 'Mo27arg Artificer with advanced tech.',
                'is_legendary' => 0,
                'photo' => 'public/Mo27arg_Artificer_full.jpg',
                'category_id' => 1,
            ),
            37 =>
            array(
                'name' => 'Moat',
                'type' => 'Spell',
                'mana' => 3,
                'attack' => 0,
                'health' => 0,
                'description' => 'Create a moat to defend your board.',
                'is_legendary' => 0,
                'photo' => 'public/Moat.jpg',
                'category_id' => 4,
            ),
            38 =>
            array(
                'name' => 'Moroes',
                'type' => 'Minion',
                'mana' => 4,
                'attack' => 2,
                'health' => 4,
                'description' => 'Moroes, the butler of Karazhan.',
                'is_legendary' => 1,
                'photo' => 'public/Moroes.jpg',
                'category_id' => 2,
            ),
            39 =>
            array(
                'name' => 'Netherspite',
                'type' => 'Minion',
                'mana' => 5,
                'attack' => 4,
                'health' => 6,
                'description' => 'Netherspite, a fearsome dragon.',
                'is_legendary' => 1,
                'photo' => 'public/Netherspite.jpg',
                'category_id' => 2,
            ),
            40 =>
            array(
                'name' => 'Onyx Magescribe',
                'type' => 'Minion',
                'mana' => 4,
                'attack' => 3,
                'health' => 5,
                'description' => 'Onyx Magescribe with powerful magic.',
                'is_legendary' => 0,
                'photo' => 'public/Onyx_Magescribe_full.jpg',
                'category_id' => 3,
            ),
            41 =>
            array(
                'name' => 'Patches',
                'type' => 'Minion',
                'mana' => 1,
                'attack' => 1,
                'health' => 1,
                'description' => 'Patches the Pirate, a troublesome menace.',
                'is_legendary' => 1,
                'photo' => 'public/Patches.jpg',
                'category_id' => 2,
            ),
            42 =>
            array(
                'name' => 'Peasant',
                'type' => 'Minion',
                'mana' => 1,
                'attack' => 1,
                'health' => 1,
                'description' => 'A humble peasant.',
                'is_legendary' => 0,
                'photo' => 'public/Peasant_full.jpg',
                'category_id' => 1,
            ),
            43 =>
            array(
                'name' => 'Plague of Death',
                'type' => 'Spell',
                'mana' => 6,
                'attack' => 0,
                'health' => 0,
                'description' => 'Summon a plague upon your enemies.',
                'is_legendary' => 0,
                'photo' => 'public/Plague_of_Death_full.jpg',
                'category_id' => 4,
            ),
            44 =>
            array(
                'name' => 'Pompous',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 3,
                'health' => 4,
                'description' => 'A pompous nobleman.',
                'is_legendary' => 0,
                'photo' => 'public/Pompous.jpg',
                'category_id' => 3,
            ),
            45 =>
            array(
                'name' => 'Prince Keleseth',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 3,
                'health' => 4,
                'description' => 'Prince Keleseth, a dark prince.',
                'is_legendary' => 1,
                'photo' => 'public/PrinceKeleseth.jpg',
                'category_id' => null,
            ),
            46 =>
            array(
                'name' => 'Ragnaros',
                'type' => 'Minion',
                'mana' => 8,
                'attack' => 8,
                'health' => 8,
                'description' => 'Ragnaros the Firelord, a powerful elemental.',
                'is_legendary' => 1,
                'photo' => 'public/Ragnaros.jpg',
                'category_id' => 2,
            ),
            47 =>
            array(
                'name' => 'Rockpool',
                'type' => 'Minion',
                'mana' => 2,
                'attack' => 2,
                'health' => 3,
                'description' => 'Rockpool Hunter, fierce in battle.',
                'is_legendary' => 0,
                'photo' => 'public/Rockpool.jpg',
                'category_id' => null,
            ),
            48 =>
            array(
                'name' => 'ShallowGravedigger',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 3,
                'health' => 4,
                'description' => 'A gravedigger who unearths dark secrets.',
                'is_legendary' => 0,
                'photo' => 'public/ShallowGravedigger.jpg',
                'category_id' => 3,
            ),
            49 =>
            array(
                'name' => 'Shield of Galakrond',
                'type' => 'Spell',
                'mana' => 3,
                'attack' => 0,
                'health' => 0,
                'description' => 'A powerful shield from Galakrond.',
                'is_legendary' => 0,
                'photo' => 'public/Shield_of_Galakrond_full.jpg',
                'category_id' => 4,
            ),
            50 =>
            array(
                'name' => 'Silas Darkmoon',
                'type' => 'Minion',
                'mana' => 4,
                'attack' => 4,
                'health' => 5,
                'description' => 'Silas Darkmoon, a trickster with dark powers.',
                'is_legendary' => 1,
                'photo' => 'public/Silas_Darkmoon_full.jpg',
                'category_id' => 2,
            ),
            51 =>
            array(
                'name' => 'SpiritLash',
                'type' => 'Spell',
                'mana' => 3,
                'attack' => 0,
                'health' => 0,
                'description' => 'Lash out with dark spiritual power.',
                'is_legendary' => 0,
                'photo' => 'public/SpiritLash.jpg',
                'category_id' => 4,
            ),
            52 =>
            array(
                'name' => 'SpiritLynx',
                'type' => 'Minion',
                'mana' => 2,
                'attack' => 3,
                'health' => 3,
                'description' => 'A quick and elusive spirit lynx.',
                'is_legendary' => 0,
                'photo' => 'public/SpiritLynx.jpg',
                'category_id' => null,
            ),
            53 =>
            array(
                'name' => 'Taelan',
                'type' => 'Minion',
                'mana' => 5,
                'attack' => 4,
                'health' => 5,
                'description' => 'Taelan, a noble paladin.',
                'is_legendary' => 0,
                'photo' => 'public/Taelan.jpg',
                'category_id' => 3,
            ),
            54 =>
            array(
                'name' => 'The Amazing Reno',
                'type' => 'Minion',
                'mana' => 6,
                'attack' => 5,
                'health' => 6,
                'description' => 'Reno, the amazing adventurer.',
                'is_legendary' => 1,
                'photo' => 'public/The_Amazing_Reno_29_full.jpg',
                'category_id' => null,
            ),
            55 =>
            array(
                'name' => 'Totemic',
                'type' => 'Minion',
                'mana' => 2,
                'attack' => 2,
                'health' => 3,
                'description' => 'Totemic power totems.',
                'is_legendary' => 0,
                'photo' => 'public/Totemic.jpg',
                'category_id' => 3,
            ),
            56 =>
            array(
                'name' => 'Transfer Student',
                'type' => 'Minion',
                'mana' => 4,
                'attack' => 3,
                'health' => 4,
                'description' => 'A student transferring with new powers.',
                'is_legendary' => 0,
                'photo' => 'public/Transfer_Student_full.jpg',
                'category_id' => null,
            ),
            57 =>
            array(
                'name' => 'Untapped Potential',
                'type' => 'Spell',
                'mana' => 2,
                'attack' => 0,
                'health' => 0,
                'description' => 'Unleash the untapped potential of your cards.',
                'is_legendary' => 0,
                'photo' => 'public/Untapped_Potential_full.jpg',
                'category_id' => 4,
            ),
            58 =>
            array(
                'name' => 'Varian King of Stormwind',
                'type' => 'Minion',
                'mana' => 9,
                'attack' => 8,
                'health' => 8,
                'description' => 'Varian, King of Stormwind, a leader in battle.',
                'is_legendary' => 1,
                'photo' => 'public/Varian2C_King_of_Stormwind_full.jpg',
                'category_id' => 2,
            ),
            59 =>
            array(
                'name' => 'WarKodo',
                'type' => 'Minion',
                'mana' => 4,
                'attack' => 5,
                'health' => 5,
                'description' => 'War Kodo, a mighty beast of battle.',
                'is_legendary' => 0,
                'photo' => 'public/WarKodo.jpg',
                'category_id' => null,
            ),
            60 =>
            array(
                'name' => 'Wretched Tutor',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 2,
                'health' => 4,
                'description' => 'Wretched Tutor, a teacher of dark arts.',
                'is_legendary' => 0,
                'photo' => 'public/Wretched_Tutor_full.jpg',
                'category_id' => 3,
            ),
            61 =>
            array(
                'name' => 'Air Raid',
                'type' => 'Spell',
                'mana' => 4,
                'attack' => 0,
                'health' => 0,
                'description' => 'Summon two 1/1 Silver Hand Recruits with Taunt.',
                'is_legendary' => 0,
                'photo' => 'public/Air_Raid_full.jpg',
                'category_id' => 1,
            ),
            62 =>
            array(
                'name' => 'Alar',
                'type' => 'Minion',
                'mana' => 5,
                'attack' => 4,
                'health' => 6,
                'description' => 'Alar, an ancient warrior.',
                'is_legendary' => 0,
                'photo' => 'public/Al27ar_full.jpg',
                'category_id' => 1,
            ),
            63 =>
            array(
                'name' => 'Alexstrasza',
                'type' => 'Minion',
                'mana' => 9,
                'attack' => 8,
                'health' => 8,
                'description' => 'Alexstrasza, the Dragonqueen.',
                'is_legendary' => 1,
                'photo' => 'public/Alexstrasza.jpg',
                'category_id' => 2,
            ),
            64 =>
            array(
                'name' => 'Altruis the Outcast',
                'type' => 'Minion',
                'mana' => 4,
                'attack' => 3,
                'health' => 4,
                'description' => 'Altruis the Outcast, a rogue demon hunter.',
                'is_legendary' => 0,
                'photo' => 'public/Altruis_the_Outcast_full.jpg',
                'category_id' => 1,
            ),
            65 =>
            array(
                'name' => 'Animated Broomstick',
                'type' => 'Minion',
                'mana' => 3,
                'attack' => 2,
                'health' => 2,
                'description' => 'Animated Broomstick, an enchanted helper.',
                'is_legendary' => 0,
                'photo' => 'public/Animated_Broomstick_full.jpg',
                'category_id' => 1,
            ),
            66 =>
            array(
                'name' => 'Arcane Amplifier',
                'type' => 'Spell',
                'mana' => 5,
                'attack' => 0,
                'health' => 0,
                'description' => 'Amplify your arcane magic power.',
                'is_legendary' => 0,
                'photo' => 'public/Arcane_Amplifier_full.jpg',
                'category_id' => 4,
            ),
            67 =>
            array(
                'name' => 'Arch VillaiRafaam',
                'type' => 'Minion',
                'mana' => 7,
                'attack' => 6,
                'health' => 7,
                'description' => 'Rafaam, a powerful villain.',
                'is_legendary' => 1,
                'photo' => 'public/Arch-Villain_Rafaam_full.jpg',
                'category_id' => 2,
            ),
        ));
    }
}
